-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.category
(
    category_id bigint NOT NULL,
    category_name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT category_pkey PRIMARY KEY (category_id),
    CONSTRAINT category_category_name_key UNIQUE (category_name)
);

CREATE TABLE IF NOT EXISTS public.customer
(
    customer_id bigint NOT NULL,
    customer_addr text COLLATE pg_catalog."default" NOT NULL,
    last_name text COLLATE pg_catalog."default" NOT NULL,
    first_name text COLLATE pg_catalog."default" NOT NULL,
    patronymic text COLLATE pg_catalog."default",
    CONSTRAINT customer_pkey PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public.manufacturer
(
    manufacturer_id bigint NOT NULL,
    manufacturer_name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT manufacturer_pkey PRIMARY KEY (manufacturer_id),
    CONSTRAINT manufacturer_manufacturer_name_key UNIQUE (manufacturer_name)
);

CREATE TABLE IF NOT EXISTS public.product
(
    product_id bigint NOT NULL,
    product_name text COLLATE pg_catalog."default" NOT NULL,
    category_id bigint NOT NULL,
    manufacturer_id bigint NOT NULL,
    product_color text COLLATE pg_catalog."default",
    product_size text COLLATE pg_catalog."default",
    CONSTRAINT product_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.product_price_change
(
    store_id bigint NOT NULL,
    product_id bigint NOT NULL,
    date_price_change timestamp without time zone NOT NULL,
    new_price numeric(12, 2) NOT NULL,
    CONSTRAINT product_price_change_pkey PRIMARY KEY (date_price_change)
);

CREATE TABLE IF NOT EXISTS public.purchase
(
    purchase_id bigint NOT NULL,
    store_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    purchase_date date NOT NULL,
    delivery_date date,
    discount numeric(6, 4) NOT NULL DEFAULT 0,
    CONSTRAINT purchase_pkey PRIMARY KEY (purchase_id)
);

CREATE TABLE IF NOT EXISTS public.purchase_item
(
    purchase_id bigint NOT NULL,
    product_id bigint NOT NULL,
    product_count integer NOT NULL,
    product_price numeric(12, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.store
(
    store_id bigint NOT NULL,
    store_name text COLLATE pg_catalog."default" NOT NULL,
    store_addr text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT store_pkey PRIMARY KEY (store_id)
);

ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT product_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.category (category_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT product_manufacturer_id_fkey FOREIGN KEY (manufacturer_id)
    REFERENCES public.manufacturer (manufacturer_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.product_price_change
    ADD CONSTRAINT product_price_change_product_fk FOREIGN KEY (product_id)
    REFERENCES public.product (product_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.product_price_change
    ADD CONSTRAINT product_price_change_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.product (product_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.product_price_change
    ADD CONSTRAINT product_price_change_store_fk FOREIGN KEY (store_id)
    REFERENCES public.store (store_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.product_price_change
    ADD CONSTRAINT product_price_change_store_id_fkey FOREIGN KEY (store_id)
    REFERENCES public.store (store_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.purchase
    ADD CONSTRAINT purchase_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customer (customer_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.purchase
    ADD CONSTRAINT purchase_store_id_fkey FOREIGN KEY (store_id)
    REFERENCES public.store (store_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.purchase_item
    ADD CONSTRAINT purchase_item_product_fk FOREIGN KEY (product_id)
    REFERENCES public.product (product_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.purchase_item
    ADD CONSTRAINT purchase_item_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.product (product_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.purchase_item
    ADD CONSTRAINT purchase_item_purchase_id_fkey FOREIGN KEY (purchase_id)
    REFERENCES public.purchase (purchase_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

END;